[package]
name = "burn-vision"
version = "0.1.0"
author = "KwachOjunga ojungakwach@gmail.com"
edition = "2024"


[workspace]
members = [
    "examples/alex",
    "crates/*",
    "examples/googlenet"
]

[dependencies]
burn = { version = "0.16.0", features = ["train", "wgpu", "ndarray", "tui"] }
