name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: sudo apt-get update && sudo apt-get install -y \
       build-essential \
       pkg-config \
       libssl-dev \
       libffi-dev \
       python3-dev
       cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
